/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_accept[293] =
    {   0,
        1,    1,   86,   85,    2,    5,    1,   85,   75,   80,
       56,   85,   85,   76,   77,   54,   52,   61,   53,   55,
       72,   62,   57,   51,   58,   84,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   78,   85,   79,    2,    1,   48,
        0,    0,   74,   50,    0,   44,   59,   41,   60,   43,
       42,    0,   72,   84,   84,   45,   47,   46,    0,   40,
        0,   40,   40,   40,   40,   40,   40,   13,   40,   40,
       40,   40,   40,   40,   21,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   49,

        0,    0,    4,    0,   41,   73,    0,   82,    0,   81,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   19,   40,   22,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,    0,    0,    0,   41,   83,    6,   40,    8,
        9,   40,   40,   40,   40,   15,   16,   40,   40,   20,
       23,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   35,   40,   40,    3,    0,
       83,    7,   10,   40,   40,   40,   40,   18,    0,   40,
       40,   40,   39,   26,   40,   40,   40,   40,   40,   40,

       33,   40,   40,   37,    0,   40,   40,   14,   17,   71,
       38,   40,   25,   27,   28,   29,   30,   31,   40,   40,
       40,    0,   40,   12,   40,   32,   40,   40,    0,   11,
       24,   34,   36,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   66,    0,    0,    0,   65,    0,
        0,    0,   63,    0,   70,   64,    0,    0,   68,   67,
       69,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    3,    1,    1,    1,    1,    5,    1,    6,    1,
        1,    1,    1,    5,    6,    4,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[298] =
    {   0,
        0,    0,  653,  654,  650,  654,  647,  628,    0,  611,
       24,  639,    0,  654,  654,  629,   44,  654,   45,   47,
       49,  654,  624,  623,  622,   50,   51,   60,   64,   67,
       68,   65,   72,   70,   88,   74,   92,   95,  108,  109,
      113,  118,  125,  117,  654,  588,  654,  640,  637,  654,
      612,  597,  654,  654,  628,  654,  654,   63,  654,  654,
      654,  618,  108,  114,  619,  654,  654,  654,  623,  126,
       65,  137,  138,  144,  147,  150,  156,  155,  160,  163,
      167,  169,  168,  172,  174,  176,  190,  196,  198,  194,
      199,  207,  216,  217,  220,  227,  228,  237,  229,  654,

      248,  602,  654,  614,   70,  180,  620,  654,  126,  654,
      233,  234,  259,  246,  262,  271,  273,  276,  279,  281,
      287,  285,  292,  295,  301,  303,  305,  308,  312,  313,
      314,  315,  317,  322,  338,  341,  339,  342,  345,  351,
      350,  352,  625,  624,  589,  609,  198,  355,  361,  363,
      364,  368,  371,  380,  382,  384,  385,  387,  388,  390,
      391,  392,  393,  401,  394,  410,  412,  415,  418,  420,
      422,  431,  439,  426,  440,  444,  445,  449,  654,  579,
      218,  451,  453,  456,  462,  463,  458,  467,  614,  469,
      470,  479,  475,  480,  483,  488,  492,  496,  499,  500,

      501,  502,  504,  509,  591,  520,  522,  521,  526,  654,
      527,  528,  529,  530,  534,  538,  539,  540,  546,  548,
      547,  589,  550,  552,  559,  560,  564,  566,  200,  568,
      569,  572,  577,  599,  116,  254,  582,  559,  572,  554,
      552,  163,  549,  216,  556,  292,  549,  552,  304,  529,
      512,  476,  470,  451,  468,  410,  405,  392,  393,  408,
      393,  390,  333,  341,  323,  300,  299,  252,  269,  242,
      255,  231,  248,  234,  654,  203,  151,  152,  654,  146,
      113,   89,  654,   78,  654,  654,   72,   65,  654,  654,
      654,  654,  604,  610,  612,  615,  619

    } ;

static yyconst short int yy_def[298] =
    {   0,
      292,    1,  292,  292,  292,  292,  292,  292,  293,  292,
      292,  292,  294,  292,  292,  292,  292,  292,  292,  292,
      295,  292,  292,  292,  292,  295,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  295,  295,  295,  292,  292,  292,  297,  296,
      292,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  292,

      292,  292,  292,  292,  292,  292,  297,  292,  292,  292,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  292,  292,  292,  292,  292,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  292,  292,
      292,  296,  296,  296,  296,  296,  296,  296,  297,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  292,  296,  296,  296,  296,  292,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  292,  296,  296,  296,  296,  296,  296,  292,  296,
      296,  296,  296,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,    0,  292,  292,  292,  292,  292

    } ;

static yyconst short int yy_nxt[711] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,    4,   20,   21,   22,
       23,   24,   25,   26,   27,    4,    4,    4,    4,   28,
       29,   30,   31,   32,   33,   34,   27,   35,   27,   36,
       37,   27,   27,   38,   39,   40,   41,   42,   43,   44,
       27,   27,   27,   45,   46,   47,   53,   57,   53,   60,
       59,   69,   58,   58,   61,   62,  292,   63,   64,   53,
       69,   53,   64,   64,   69,   69,   71,   69,   69,  104,
       69,  105,   69,  109,   69,   71,  104,  291,  105,   71,
       71,  110,   71,   71,  290,   71,   74,   71,   69,   71,

      289,   77,   69,   75,   79,   69,   80,   72,   73,   76,
       78,   82,   84,   71,   83,   81,   87,   71,   69,   69,
       71,   88,   85,   69,   62,  288,   63,   69,   69,   86,
      292,   64,   64,   71,   71,   69,   69,   64,   71,   89,
       91,   90,   71,   71,  109,   92,   93,   69,   69,  287,
       71,   71,  110,   99,   69,   94,  237,   69,   95,   97,
       69,  238,   71,   71,   96,   69,   69,   98,  286,   71,
       69,  112,   71,   69,  285,   71,  114,   69,   69,   69,
       71,   71,   69,  111,   69,   71,   69,  284,   71,  113,
      116,  115,   71,   71,   71,  246,  147,   71,  106,   71,

       69,   71,  117,  234,   69,  118,   69,  247,   69,   69,
      119,  121,  122,  120,  181,   71,  181,   69,  123,   71,
      235,   71,  124,   71,   71,  283,   69,   69,  130,  128,
       69,  125,   71,  126,  181,  127,  181,   69,   69,   69,
      129,   71,   71,   69,   69,   71,  134,   69,  249,  131,
      282,  132,   71,   71,   71,  143,   69,  136,   71,   71,
      250,  135,   71,  149,  281,  138,  142,  280,  133,   69,
      137,   71,   69,  139,  140,  148,  141,  279,  278,  144,
      144,   69,  144,   69,   71,  277,   69,   71,  276,   69,
      151,   69,  150,  144,  239,   69,   71,   69,   71,  240,

      154,   71,   69,  155,   71,   69,   71,  152,  153,  156,
       71,   69,   71,   69,  158,   69,  159,   71,   69,  157,
       71,  275,   69,   69,   69,   69,   71,   69,   71,  252,
       71,  253,   69,   71,  160,  274,  161,   71,   71,   71,
       71,  256,   71,  257,  162,  164,  163,   71,   69,   69,
      169,   69,   69,  273,  166,   69,  168,  272,  167,  165,
       69,   69,   69,   71,   71,   69,   71,   71,  170,  271,
       71,   69,  173,   69,   69,   71,   71,   71,   69,  177,
       71,   69,  175,  176,  174,  171,   71,  172,   71,   71,
       69,  178,   69,   71,   69,   69,   71,   69,   69,  182,

       69,   69,  189,   69,   69,   71,  270,   71,  184,   71,
       71,   69,   71,   71,  183,   71,   71,   71,   71,   71,
       69,  186,   69,  269,  268,   69,   71,  185,   69,  267,
       69,  187,   69,  266,  188,   71,   69,   71,  192,  190,
       71,   69,  265,   71,  193,   71,  191,   71,  195,   69,
       69,   71,  264,  198,   69,   69,   71,  197,  194,   69,
      196,   69,  199,   69,   71,   71,   69,  201,   69,   71,
       71,  200,   69,   69,   71,  202,   71,   69,   71,   69,
       69,   71,  204,   71,  263,   69,  262,   71,   71,   69,
       69,  203,   71,   69,   71,   71,  208,  206,   69,  209,

       71,  207,   69,  211,   71,   71,   69,  261,   71,   69,
       69,   69,   69,   71,   69,  214,  212,   71,  260,   69,
      213,   71,  215,  216,   71,   71,   71,   71,  259,   71,
       69,   69,   69,  219,   71,  218,   69,   69,   69,   69,
       69,  221,  217,  220,   69,   71,   71,   71,   69,   69,
       69,   71,   71,   71,   71,   71,   69,   69,   69,   71,
       69,  225,   69,   71,   71,   71,  258,  223,  224,   69,
       69,   71,   71,   71,   69,   71,   69,   71,   69,   69,
      226,  227,   69,  230,   71,   71,  228,   69,  255,   71,
      254,   71,  251,   71,   71,  248,  232,   71,  245,  233,

      244,  243,   71,  231,   51,  242,   51,   51,   51,   51,
       55,  241,   55,   55,   55,   55,   65,   65,   70,  236,
       70,  107,  229,  222,  107,  210,  205,  146,  180,  179,
      179,  108,  146,  145,  108,  292,  106,  103,  102,  101,
       49,   48,  100,   68,   67,   66,   56,   54,   52,   50,
       49,   48,  292,    3,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292
    } ;

static yyconst short int yy_chk[711] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   11,   17,   11,   20,
       19,   27,   17,   19,   20,   21,   26,   21,   26,   11,
       28,   11,   21,   26,   29,   32,   27,   30,   31,   58,
       34,   58,   33,   71,   36,   28,  105,  288,  105,   29,
       32,   71,   30,   31,  287,   34,   30,   33,   35,   36,

      284,   31,   37,   30,   32,   38,   32,   28,   29,   30,
       31,   33,   34,   35,   33,   32,   36,   37,   39,   40,
       38,   37,   35,   41,   63,  282,   63,   44,   42,   35,
       64,   63,   64,   39,   40,   43,   70,   64,   41,   38,
       40,   39,   44,   42,  109,   40,   40,   72,   73,  281,
       43,   70,  109,   44,   74,   40,  235,   75,   40,   42,
       76,  235,   72,   73,   41,   78,   77,   43,  280,   74,
       79,   73,   75,   80,  278,   76,   75,   81,   83,   82,
       78,   77,   84,   72,   85,   79,   86,  277,   80,   74,
       77,   76,   81,   83,   82,  242,  106,   84,  106,   85,

       87,   86,   78,  229,   90,   79,   88,  242,   89,   91,
       80,   82,   83,   81,  147,   87,  147,   92,   84,   90,
      229,   88,   86,   89,   91,  276,   93,   94,   91,   90,
       95,   87,   92,   88,  181,   89,  181,   96,   97,   99,
       90,   93,   94,  111,  112,   95,   94,   98,  244,   92,
      274,   93,   96,   97,   99,  101,  114,   95,  111,  112,
      244,   94,   98,  112,  273,   97,   99,  272,   93,  113,
       96,  114,  115,   97,   98,  111,   98,  271,  270,  101,
      101,  116,  101,  117,  113,  269,  118,  115,  268,  119,
      114,  120,  113,  101,  236,  122,  116,  121,  117,  236,

      116,  118,  123,  117,  119,  124,  120,  115,  115,  118,
      122,  125,  121,  126,  120,  127,  121,  123,  128,  119,
      124,  267,  129,  130,  131,  132,  125,  133,  126,  246,
      127,  246,  134,  128,  123,  266,  125,  129,  130,  131,
      132,  249,  133,  249,  126,  128,  127,  134,  135,  137,
      133,  136,  138,  265,  130,  139,  132,  264,  131,  129,
      141,  140,  142,  135,  137,  148,  136,  138,  134,  263,
      139,  149,  137,  150,  151,  141,  140,  142,  152,  141,
      148,  153,  139,  140,  138,  135,  149,  136,  150,  151,
      154,  142,  155,  152,  156,  157,  153,  158,  159,  149,

      160,  161,  162,  163,  165,  154,  262,  155,  153,  156,
      157,  164,  158,  159,  152,  160,  161,  162,  163,  165,
      166,  155,  167,  261,  260,  168,  164,  154,  169,  259,
      170,  158,  171,  258,  159,  166,  174,  167,  165,  163,
      168,  172,  257,  169,  166,  170,  164,  171,  168,  173,
      175,  174,  256,  171,  176,  177,  172,  170,  167,  178,
      169,  182,  172,  183,  173,  175,  184,  174,  187,  176,
      177,  173,  185,  186,  178,  175,  182,  188,  183,  190,
      191,  184,  178,  187,  255,  193,  254,  185,  186,  192,
      194,  177,  188,  195,  190,  191,  186,  184,  196,  187,

      193,  185,  197,  190,  192,  194,  198,  253,  195,  199,
      200,  201,  202,  196,  203,  195,  191,  197,  252,  204,
      192,  198,  196,  197,  199,  200,  201,  202,  251,  203,
      206,  208,  207,  200,  204,  199,  209,  211,  212,  213,
      214,  203,  198,  202,  215,  206,  208,  207,  216,  217,
      218,  209,  211,  212,  213,  214,  219,  221,  220,  215,
      223,  212,  224,  216,  217,  218,  250,  206,  207,  225,
      226,  219,  221,  220,  227,  223,  228,  224,  230,  231,
      219,  220,  232,  223,  225,  226,  221,  233,  248,  227,
      247,  228,  245,  230,  231,  243,  227,  232,  241,  228,

      240,  239,  233,  225,  293,  238,  293,  293,  293,  293,
      294,  237,  294,  294,  294,  294,  295,  295,  296,  234,
      296,  297,  222,  205,  297,  189,  180,  146,  145,  144,
      143,  107,  104,  102,   69,   65,   62,   55,   52,   51,
       49,   48,   46,   25,   24,   23,   16,   12,   10,    8,
        7,    5,    3,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyser.l"
#define INITIAL 0
/*Implemenatation of Lexical Analyser for C Language*/
/*Program identifies tokens to be returned by the scanner*/
/*Also stores the values in Symbol Table*/
/*Program also identifies errors in C file*/
#line 7 "lexicalAnalyser.l"
int lineno = 1;
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#define Automation 1
#define Breakpoint 2
#define Situation 3
#define Unicode 4
#define Immutable 5
#define Endless 6
#define Predesigned 7
#define Perform 8
#define Twice 9
#define Alternatively 10
#define Enumeration 11
#define External 12
#define Decimal 13
#define Loop 14
#define Jump 15
#define Conditional 16
#define Countable 17
#define Extended 18
#define Memory 19
#define Exit 20
#define Small  21
#define Signed 22
#define Capacity 23
#define Fixed 24
#define Structure 25
#define Select 26
#define Alias 27
#define Shared 28
#define NonNegative 29
#define Empty 30
#define Unpredictable 31
#define Repeat 32

#define Name 33
#define SingleNote 34
#define Multinote 35
#define Multinoteclose 36

#define LessEqual 37
#define GreaterEqual 38
#define Alike 39
#define Unlike 40
#define Otherwise 41
#define Likewise 42
#define Allocate 43
#define Total 44
#define Below 45
#define Many 46
#define Split 47
#define Remainder 48
#define Lower 49
#define Higher 50
#define Raise 51
#define Reduce 52

#define Separator 53
#define Partial 54

#define Label 55
#define Major 56

#define Printf 57
#define Scanf 58
#define Describe 59

#define IntConst 60
#define FloatConst 61

#define TypeSpec 62

#define DQ 63

#define OBO 64
#define OBC 65
#define CBO 66
#define CBC 67
#define HASH 68

#define ARR 69
#define FUNC 70

#define NumErr 71
#define UNKNOWN 72

#define CharConst 73
#define SignedConst 74
#define StringConst 75
#line 715 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 111 "lexicalAnalyser.l"

#line 868 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 293 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 654 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 112 "lexicalAnalyser.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "lexicalAnalyser.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "lexicalAnalyser.l"
return StringConst;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "lexicalAnalyser.l"
return CharConst;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "lexicalAnalyser.l"
{lineno++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 117 "lexicalAnalyser.l"
return Automation;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 118 "lexicalAnalyser.l"
return Breakpoint;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "lexicalAnalyser.l"
return Situation;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 120 "lexicalAnalyser.l"
return Unicode;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 121 "lexicalAnalyser.l"
return Immutable;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 122 "lexicalAnalyser.l"
return Endless;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 123 "lexicalAnalyser.l"
return Predesigned;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "lexicalAnalyser.l"
return Perform;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "lexicalAnalyser.l"
return Twice;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "lexicalAnalyser.l"
return Alternatively;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 127 "lexicalAnalyser.l"
return Enumeration;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 128 "lexicalAnalyser.l"
return External;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 129 "lexicalAnalyser.l"
return Decimal;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 130 "lexicalAnalyser.l"
return Loop;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 131 "lexicalAnalyser.l"
return Jump;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "lexicalAnalyser.l"
return Conditional;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 133 "lexicalAnalyser.l"
return Countable;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "lexicalAnalyser.l"
return Extended;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lexicalAnalyser.l"
return Memory;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "lexicalAnalyser.l"
return Exit;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "lexicalAnalyser.l"
return Small;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 138 "lexicalAnalyser.l"
return Signed;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 139 "lexicalAnalyser.l"
return Capacity;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 140 "lexicalAnalyser.l"
return Fixed;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 141 "lexicalAnalyser.l"
return Structure;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "lexicalAnalyser.l"
return Select;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 143 "lexicalAnalyser.l"
return Alias;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "lexicalAnalyser.l"
return Shared;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 145 "lexicalAnalyser.l"
return NonNegative;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "lexicalAnalyser.l"
return Empty;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 147 "lexicalAnalyser.l"
return Unpredictable;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 148 "lexicalAnalyser.l"
return Repeat;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 150 "lexicalAnalyser.l"
return Printf;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 151 "lexicalAnalyser.l"
return Scanf;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "lexicalAnalyser.l"
return Name;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "lexicalAnalyser.l"
return SignedConst;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "lexicalAnalyser.l"
return SingleNote;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 158 "lexicalAnalyser.l"
return Multinote;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 159 "lexicalAnalyser.l"
return Multinoteclose;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 161 "lexicalAnalyser.l"
return LessEqual;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 162 "lexicalAnalyser.l"
return GreaterEqual;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 163 "lexicalAnalyser.l"
return Alike;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 164 "lexicalAnalyser.l"
return Unlike;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 165 "lexicalAnalyser.l"
return Otherwise;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 166 "lexicalAnalyser.l"
return Likewise;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 167 "lexicalAnalyser.l"
return Allocate;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "lexicalAnalyser.l"
return Total;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 169 "lexicalAnalyser.l"
return Below;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 170 "lexicalAnalyser.l"
return Many;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 171 "lexicalAnalyser.l"
return Split;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 172 "lexicalAnalyser.l"
return Remainder;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 173 "lexicalAnalyser.l"
return Lower;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 174 "lexicalAnalyser.l"
return Higher;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 175 "lexicalAnalyser.l"
return Raise;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 176 "lexicalAnalyser.l"
return Reduce;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 178 "lexicalAnalyser.l"
return Separator;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 179 "lexicalAnalyser.l"
return Partial;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 181 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 182 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 183 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 184 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 185 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "lexicalAnalyser.l"
return Label;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 190 "lexicalAnalyser.l"
return Major;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "lexicalAnalyser.l"
return IntConst;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "lexicalAnalyser.l"
return FloatConst;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 195 "lexicalAnalyser.l"
return TypeSpec;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 196 "lexicalAnalyser.l"
return DQ;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 197 "lexicalAnalyser.l"
return OBO;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 198 "lexicalAnalyser.l"
return OBC;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 199 "lexicalAnalyser.l"
return CBO;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 200 "lexicalAnalyser.l"
return CBC;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 201 "lexicalAnalyser.l"
return HASH;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 203 "lexicalAnalyser.l"
return ARR;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 204 "lexicalAnalyser.l"
return FUNC;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 205 "lexicalAnalyser.l"
return NumErr;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 206 "lexicalAnalyser.l"
return UNKNOWN;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 207 "lexicalAnalyser.l"
ECHO;
	YY_BREAK
#line 1376 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 293 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 293 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 292);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 207 "lexicalAnalyser.l"


struct node
{
	char token[100];
    	char attr[100];
	struct node *next;
};

struct hash
{
	struct node *head;
	int count;
};

struct hash hashTable[1000];
int eleCount = 1000;

struct node * createNode(char *token, char *attr)
{
	struct node *newnode;
	newnode = (struct node *) malloc(sizeof(struct node));
	strcpy(newnode->token, token);
	strcpy(newnode->attr, attr);
	newnode->next = NULL;
	return newnode;
}

int hashIndex(char *token)
{
	int hi=0;
	int l,i;
	for(i=0;token[i]!='\0';i++)
	{
		hi = hi + (int)token[i];
	}
	hi = hi%eleCount;
	return hi;
}

void hashInsert(char *token, char *attr)
{
	int flag=0;
	int hi;
	hi = hashIndex(token);
	struct node *newnode = createNode(token, attr);
	/* head of list for the bucket with index "hashIndex" */
	if (hashTable[hi].head==NULL)
	{
		hashTable[hi].head = newnode;
	        hashTable[hi].count = 1;
	        return;
	}
	struct node *myNode;
    	myNode = hashTable[hi].head;
	while (myNode != NULL)
    	{
        	if (strcmp(myNode->token, token)==0)
        	{
            		flag = 1;
            		break;
        	}
        	myNode = myNode->next;
    	}
	if(!flag)
	{
		//adding new node to the list
		newnode->next = (hashTable[hi].head);
		//update the head of the list and no of nodes in the current bucket
		hashTable[hi].head = newnode;
		hashTable[hi].count++;
	}
	return;
}

void display()
{
    	struct node *myNode;
    	int i,j, k=1;
    	printf("-------------------------------------------------------------------");
    	printf("\nSNo \t|\tToken \t\t|\tToken Type \t\n");
        printf("-------------------------------------------------------------------\n");
    	for (i = 0; i < eleCount; i++)
    	{
        	if (hashTable[i].count == 0)
            		continue;
        	myNode = hashTable[i].head;
        	if (!myNode)
            		continue;
        	while (myNode != NULL)
        	{
            		printf("%d\t\t", k++);
            		printf("%s\t\t\t", myNode->token);
            		printf("%s\t\n", myNode->attr);
            		myNode = myNode->next;
        	}
	}
   	return;
}

int main()
{
	int scan, slcline=0, mlc=0, mlcline=0, dq=0, dqline=0;
	yyin = fopen("test6.c","r");
	printf("\n\n");
	scan = yylex();
	while(scan)
	{
		if(lineno == slcline)
		{
			scan = yylex();
			continue;
		}
		if(lineno!=dqline && dqline!=0)
		{
			if(dq%2!=0)
				printf("\n<<<<<<<<<< ERROR! >>>>>>>>>> \n<<<<<<<<<<INCOMPLETE STRING at Line %d >>>>>>>>>>\n\n", dqline);
			dq=0;
		}
		if((scan>=1 && scan<=32) && mlc==0)
		{
			printf("%s\t\t\tKEYWORD\t\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "KEYWORD");
		}
		if(scan==33 && mlc==0)
		{
			printf("%s\t\t\tIDENTIFIER\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "IDENTIFIER");
		}
		if(scan==34)
		{
			printf("%s\t\t\tSingleline Comment\t\tLine %d\n", yytext, lineno);
			slcline = lineno;
		}
		if(scan==35 && mlc==0)
		{
			printf("%s\t\t\tMultiline Comment Start\t\tLine %d\n", yytext, lineno);
			mlcline = lineno;
			mlc = 1;
		}
		if(scan==36 && mlc==0)
		{
			printf("\n<<<<<<<<<< ERROR! >>>>>>>>>> \n<<<<<<<<<<UNMATCHED MULTILINE COMMENT END %s at Line %d >>>>>>>>>>\n\n", yytext, lineno);
		}
		if(scan==36 && mlc==1)
		{
			mlc = 0;
			printf("%s\t\t\tMultiline Comment End\t\tLine %d\n", yytext, lineno);
		}
		if((scan>=37 && scan<=52) && mlc==0)
		{
			printf("%s\t\t\tOPERATOR\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "OPERATOR");
		}
		if((scan==53||scan==54||scan==63||(scan>=64 && scan<=68)) && mlc==0)
		{
			printf("%s\t\t\tSPECIAL SYMBOL\t\t\tLine %d\n", yytext, lineno);
			if(scan==63)
			{
				dq++;
				dqline = lineno;
			}
			hashInsert(yytext, "SPECIAL SYMBOL");
		}
		if(scan==55 && mlc==0)
		{
			printf("%s\tHEADER\t\t\t\tLine %d\n",yytext, lineno);
		}
		if(scan==56 && mlc==0)
		{
			printf("%s\t\t\tMAIN FUNCTION\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "IDENTIFIER");
		}
		if((scan==57 || scan==58) && mlc==0)
		{
			printf("%s\t\t\tPRE DEFINED FUNCTION\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "PRE DEFINED FUNCTION");
		}
		if(scan==59 && mlc==0)
		{
			printf("%s\t\t\tPRE PROCESSOR DIRECTIVE\t\tLine %d\n", yytext, lineno);
		}
		if(scan==60 && mlc==0)
		{
			printf("%s\t\t\tINTEGER CONSTANT\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "INTEGER CONSTANT");
		}
		if(scan==61 && mlc==0)
		{
			printf("%s\t\t\tFLOATING POINT CONSTANT\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "FLOATING POINT CONSTANT");
		}
		if(scan==62 && mlc==0)
		{
			printf("%s\t\t\tTYPE SPECIFIER\t\t\tLine %d\n", yytext, lineno);
		}
		if(scan==69 && mlc==0)
		{
			printf("%s\t\t\tARRAY\t\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "ARRAY");
		}
		if(scan==70 && mlc==0)
		{
			printf("%s\t\t\tUSER DEFINED FUNCTION\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "USER DEFINED FUNCTION");
		}
		if(scan==71 && mlc==0)
		{
			printf("\n<<<<<<<<<< ERROR! >>>>>>>>>> \n<<<<<<<<<<CONSTANT ERROR %s at Line %d >>>>>>>>>>\n\n", yytext, lineno);
		}
		if(scan==72 && mlc==0)
		{
			printf("\n<<<<<<<<<< ERROR! >>>>>>>>>> \n<<<<<<<<<<UNKNOWN TOKEN %s at Line %d >>>>>>>>>>\n\n", yytext, lineno);
		}
		if(scan==73 && mlc==0)
		{
			printf("%s\t\t\tCHARACTER CONSTANT\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "CHARACTER CONSTANT");
		}
		if(scan==74 && mlc==0)
		{
			printf("%s\t\t\tSIGNED CONSTANT\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "SIGNED CONSTANT");
		}
		if(scan==75 && mlc==0)
		{
			printf("%s\t\t\tSTRING CONSTANT\t\t\tLine %d\n", yytext, lineno);
			hashInsert(yytext, "STRING CONSTANT");
		}
		scan = yylex();
	}
	if(mlc==1)
		printf("\n<<<<<<<<<< ERROR! >>>>>>>>>> \n<<<<<<<<<<UNMATCHED COMMENT STARTING at Line %d >>>>>>>>>>\n\n",mlcline);
	printf("\n");
	printf("\n\t############## SYMBOL TABLE ##############\t\t\n");
	display();
        printf("-------------------------------------------------------------------\n\n");
}
int yywrap()
{
	return 1;
}
