/* CODENEX - Created by Sanaya Bhardwaj  */

all:
	gcc -g -o compiler driver.c lexer.c parser.c keyword_table.c nary_tree.c stack.c ast.c symbol_table.c type_checker.c semantic_analyzer.c printer.c error_handler.c code_gen.c
